import{i,S as f}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();function u(t){const s="https://pixabay.com/",r="/api/",n=new URLSearchParams({key:"44056187-241b6d2c7b447ed7c2385a3f0",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}),e=`${s}${r}?${n}`;return fetch(e).then(o=>o.json())}function m(t){return`
    <li class="gallery-item">
        <a href="${t.largeImageURL}">
            <img src="${t.webformatwURL}" alt="${t.tags}"/>
            <p class="info-title">Likes:<span class="info-value> ${t.likes}</p>
                <p class="info-title">Views:<span class="info-value> ${t.views}</p>
                <p class="info-title">Coments:<span class="info-value> ${t.comments}</p>
                <p class="info-title">Downloads:<span class="info-value> ${t.downloads}</p>           
        </a>>
    </li>`}function p(t){return t.map(m).join("")}const d=document.querySelector(".form"),l=document.querySelector(".gallery"),c=document.querySelector(".loader");y();d.addEventListener("submit",g);function g(t){t.preventDefault();const s=t.target.elements.query.value.trim();if(!s){i.show({message:"Please enter data",backgroundColor:"##ffa000;",messageSize:"16px",messageColor:"#fafafb",messageLineHeight:"150%",position:"bottomRight"});return}l.innerHTML="",h(),u(s).then(r=>{const n=p(r.hits);r.hits.length===0?i.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",messageSize:"16px",messageColor:"#fafafb",messageLineHeight:"150%",position:"bottomRight"}):(l.innerHTML=n,new f(".gallery a",{captionsData:"alt",captionDelay:250}).refresh())})}function h(){c.style.display="block"}function y(){c.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
